### ISSUE TITLE
Get machine Tests sorted

### ISSUE THREAD

**Issue by codethread** [codethread/pomo-electron#7]
**Is your feature request related to a problem? Please describe.**
This was a quick POC, but now it's working and the feature set is getting locked down, it's time to re-write most of the logic with tests

**[ideally] Describe the solution you'd like**
Get CI passing with linting/testing/e2e/backstop tests

**Tasks*
- [x] electron coverage to 💯 
- [ ] machine coverage to 💯 
- [ ] move heavy testing out of components, into machine tests
